CREATE TABLE [USER] (
	ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	NICKNAME VARCHAR(32)
);

CREATE TABLE [TASK_STATUSES] (
	ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	STATUS_NAME VARCHAR(32)
);

CREATE TABLE [TASK_TYPES] (
	ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	[TYPE_NAME] VARCHAR(32)
);

CREATE TABLE [TASK] (
    ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	CREATED_DATE DATE,
	REQUIRED_BY_DATE DATE,
	TASK_DESCRIPTION VARCHAR(256),
	TASK_STATUS INT FOREIGN KEY REFERENCES [TASK_STATUSES](ID),
	TASK_TYPE INT FOREIGN KEY REFERENCES [TASK_TYPES](ID),
	NEXT_ACTION_DATE DATE
);

CREATE TABLE [ASSIGNMENTS_RELATIONS] (
	ID_TASK INT FOREIGN KEY REFERENCES [TASK](ID),
	ID_USER INT FOREIGN KEY REFERENCES [USER](ID)
);

CREATE TABLE [COMMENT_TYPES] (
	ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	[TYPE_NAME] VARCHAR(32)
);

CREATE TABLE [COMMENT] (
    ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	ASSOCIATED_TO INT FOREIGN KEY REFERENCES [TASK](ID),
	COMMENT_OWNER INT FOREIGN KEY REFERENCES [USER](ID),
	ADDED_DATE DATE,
	COMMENT_TEXT VARCHAR(256),
	COMMENT_TYPE INT FOREIGN KEY REFERENCES [COMMENT_TYPES](ID),
	REMINDER_DATE DATE
);

INSERT INTO [USER] VALUES('Daniel');
INSERT INTO TASK_STATUSES VALUES ('Active');
INSERT INTO TASK_TYPES VALUES ('Research');
INSERT INTO [TASK] VALUES(CONVERT(DATETIME,'18/06/15 10:34:09 PM', 3), CONVERT(DATETIME,'18/06/16 10:34:09 PM', 3), 'task descr..', 1, 1, CONVERT(DATETIME,'18/12/15 10:34:09 PM', 3));

INSERT INTO COMMENT_TYPES VALUES ('bug');
INSERT INTO COMMENT_TYPES VALUES ('good practice');
INSERT INTO COMMENT VALUES (1, 1, CONVERT(DATETIME,'18/06/15 10:34:09 PM', 3), 'hello, this is the first test comment!', 2, CONVERT(DATETIME,'18/06/16 10:34:09 PM', 3));

INSERT INTO [ASSIGNMENTS_RELATIONS] VALUES(1, 1);

SELECT * FROM [TASK_TYPES];
SELECT * FROM [TASK_STATUSES];

SELECT * FROM [TASK];
SELECT * FROM [USER];
SELECT * FROM [ASSIGNMENTS_RELATIONS];
SELECT * FROM COMMENT;

--DROP TABLE [ASSIGNMENTS_RELATIONS];
--DROP TABLE [COMMENT];
--DROP TABLE [TASK];
--DROP TABLE [USER];
--DROP TABLE [TASK_TYPES];
--DROP TABLE [TASK_STATUSES];
--DROP TABLE [COMMENT_TYPES];